name = "kvcounter"
language = "rust"
type = "actor"
version = "0.1.1"

[actor]
wit_world = "hello"
wasm_target = "wasm32-wasi-preview2"
claims = [
    "wasmcloud:httpserver",
    "wasmcloud:keyvalue",
    "wasmcloud:builtin:logging",
]
