apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kvhello
spec:
  source:
    path: .
    repoURL: https://github.com/thomastaylor312/wasmio2024-demo
    targetRevision: HEAD
    directory:
      recurse: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  project: default
